AWSTemplateFormatVersion: '2010-09-09'
Description: 'State: Client security group'
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
    Default: 'vpc-3az'
Resources:
  ClientSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId: { 'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC' }
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  ClientSecurityGroup:
    Description: 'Use this Security Group to reference client traffic.'
    Value: !Ref ClientSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ClientSecurityGroup'
